# Generated by Django 2.0.6 on 2018-06-16 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe2fa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maskeduser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='session',
            name='user',
        ),
        migrations.DeleteModel(
            name='MaskedUser',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
